update CI workflow to check container status and remove detached mode from Docker Compose

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -20,12 +20,20 @@ jobs:
         uses: docker/setup-buildx-action@v2
 
       - name: Run Docker Compose
-        run: docker-compose up -d
+        run: docker-compose up
         env:
           POSTGRES_USER: discordbot-mdn
           POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
           POSTGRES_DB: discordbot-mdn-db
           BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
 
-      - name: Check Container Logs
-        run: docker-compose logs
+      - name: Check Container Status
+        run: |
+          docker ps --filter "status=exited" --filter "status=dead"
+          if [ "$(docker ps -q --filter 'status=exited')" ]; then
+            echo "Error: Some containers exited unexpectedly."
+            exit 1
+          fi
+
+      - name: Stop Docker Compose
+        run: docker-compose down
